org: souzfinance
app: souz-finance-api
service: souz-finance-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    CORS_ORIGIN: ${env:CORS_ORIGIN, '*'}
  vpc:
    securityGroupIds:
      - sg-04442ff3260b8dfd9
    subnetIds:
      - subnet-0670082f68982a670
      - subnet-09f1439d921500b5f
      - subnet-05ea235eca12005a4

functions:
  api:
    handler: handler.handler
    timeout: 29
    events:
      - httpApi:
          path: /
          method: any
      - httpApi:
          path: /{proxy+}
          method: any
